### ISSUE TITLE
Avoid new tabs when using navigation menu links

### ISSUE THREAD

**Issue by wdconinc** [eic/eic.github.io#3]
The links under Software to Pythia6, PEPSI, and BeAST are all to local pages but open in new tabs.

If possible, an external link or link to new tab should be indicated as such.

**Comment by buddhasystem** [comment]
I'll see how to make the target=_blank configurable and consistent. Thanks.

**Comment by buddhasystem** [comment]
> The links under Software to Pythia6, PEPSI, and BeAST are all to local pages but open in new tabs.
> 
> If possible, an external link or link to new tab should be indicated as such.

Wouter, I found a small bug in the menu logic, will fix shortly.

**Comment by buddhasystem** [comment]
> The links under Software to Pythia6, PEPSI, and BeAST are all to local pages but open in new tabs.
> 
> If possible, an external link or link to new tab should be indicated as such.

The stray new tabs are gone now, bug fixed.
