### ISSUE TITLE
SWG tutorials picture missing from newsletter

### ISSUE THREAD

**Issue by pinkenburg** [eic/eic.github.io#9]
in none of the newsletters, e.g.
https://eic.github.io/2020/07/31/software-news.html
the image under tutorials shows (does not render). Problem with SWG-Tutorials.pdf?

**Comment by wdconinc** [comment]
Needs png not pdf

![SWG-Tutorials](https://user-images.githubusercontent.com/4656391/89329357-4fa48380-d654-11ea-87a1-15f6b77b80e7.png)

**Comment by mdiefent** [comment]
Thank you for bringing this up, Chris. The PDF rendered in my browser and thus I have never noticed this. Thank you very much for solving this Wouter. I have merged your changes in.
